### ISSUE TITLE
The possibility to use event machine (temporary) without event store aspect 

### ISSUE THREAD

**Issue by ebezdomnikov** [proophsoftware/event-machine#110] opened 2018-11-23 21:53 UTC
Hello, guys.

I have the workable application and I would like to move it to event machine. But it's a huge step and make it as a one step would be problematic. As far as I know the current implementation (I've tried it) not allow it. Is it possible to disable events and use the only command -> handler feature?
The code example what I trying to have at the end (how I see it at least). 
```
 $eventMachine->process(Command::ADD_BUILDING)
            ->withNew(self::BUILDING) 
            ->identifiedBy('buildingId')
            ->handle([Building::class, 'add'])
//            ->recordThat(Event::BUILDING_ADDED) <- disabled event store
            ->apply([Building::class, 'whenBuildingAdded']); 
```
Thank you in advance.

**Comment by codeliner** [comment] 2018-11-26 12:47
Hey @ebezdomnikov thank you for your request.

Just to make sure: Within your command handlers you want to use ORM baked entities, like Doctrine entities? 

The problem is, Event Machine is based on the idea of a [functional core](https://proophsoftware.github.io/event-machine/api/functional_flavour.html#3-3-4)

You cannot/should not use I/O related services like an entity repository in the core of the system. To enforce this rule Event Machine does not provide a way to inject services into the domain model. You can only work with so called [context providers](https://proophsoftware.github.io/event-machine/api/functional_flavour.html#3-3-5), which are called beforehand. 

That said, the only option I can think of is to provide some kind of alternative command handling. 
Event Machine can invoke `command preprocessors`. The idea is that a preprocessor can enrich a command with additional information (f.e. specific metadata not sent by the client) before it is passed to the domain model. 
We could tell Event Machine to only invoke a command preprocessor but stop right after that. The API would look like this (needs to be added to Event Machine but is an "easy-pick"):

```php
$eventMachine->process(Command::ADD_BUILDING)
    ->onlyWithPreProcessor(Acme\PreProcessor::class);
```

What you do within the preprocessor is out of scope of Event Machine. You could even use your own `Flavour` so that your command handlers don't need to implement a specific interface and don't need to return anything (a preprocessor normally should return a modified command that is than passed on to an aggregate function).

What do you think? Would that be useful for your case?

**Comment by ebezdomnikov** [comment] 2018-11-26 16:50
Hi @codeliner!

Thank you for the quick response. Actually, the "onlyWithPreProcessor" feature is what I need to start the migration and to get all event machine functionality on board for the future!

Looking forward to that feature:)

Thanks a lot.

**Closed as completed** 2018-11-27 20:41 UTC

**Comment by codeliner** [comment] 2018-11-27 21:08
@ebezdomnikov New release available: https://github.com/proophsoftware/event-machine/releases/tag/v0.21.0

the linked PR contains a new test case and a small addition to Event Machine.

A preprocessor can add a command metadata flag `return $command->withAddedMetadata(EventMachine::CMD_METADATA_STOP_DISPATCH, true);`

to tell Event Machine that command dispatch should be stopped.

I've also prepared a [gist](https://gist.github.com/codeliner/144b90ab4dee3fd3016f0df1e4d340c9) for you. With a custom Flavour you can hook into preprocessor calls and f.e. check if a preprocessor implements a command handler interface (or whatever you want to use). This way you can migrate step by step. Let me know if something is unclear.

**Comment by ebezdomnikov** [comment] 2018-11-29 19:04
@codeliner Hi!

Thank you very much!!!
